### ISSUE TITLE
node/edge deletion crashes app

### ISSUE THREAD

**Issue by micheldumontier** [AlfaSquaD/yarrrml_mapping_application#2]
![image](https://github.com/AlfaSquaD/yarrrml_mapping_application/assets/993852/6d59d3da-bb69-47f7-ad27-1eac5faa89a9)

![image](https://github.com/AlfaSquaD/yarrrml_mapping_application/assets/993852/98583dde-4c89-490d-98de-03aa0a960812)

![image](https://github.com/AlfaSquaD/yarrrml_mapping_application/assets/993852/9ea231fd-6bc7-4370-9766-9a20214e5216)

**Comment by micheldumontier** [comment]
mmm... guess i broke it

![image](https://github.com/AlfaSquaD/yarrrml_mapping_application/assets/993852/d4c24edd-0f6d-42c3-8675-51b57cdd940c)

**Comment by AlfaSquaD** [comment]
Yeah, I was expecting this. I'll look into it.
Also, I think mapFrom and mapTo fields are wrong. You need to use those to join two nodes and generally those two fields should be primary key-foreign key. Generally for tabular data, if you are using one source then all of them should be pointing to primary key of the source. For json it might be different depending source architectire. You can find two examples attached to clarify.

![image](https://github.com/AlfaSquaD/yarrrml_mapping_application/assets/49997997/3b0b7412-bd8c-48d3-b537-0db84f83427a)

![image](https://github.com/AlfaSquaD/yarrrml_mapping_application/assets/49997997/5a306a40-5ce5-4181-8dea-f52ddea4eaab)
"hasSubjectPsuedoIdentifier" uses the primary key of source but "has code" predicate uses the unique value listed in the data for the gender

**Comment by AlfaSquaD** [comment]
@micheldumontier I also pushed a new version that improves the logging and error handling. It should make tracing easier.
